@startuml
skinparam classAttributeIconSize 0
hide circle
hide methods

class Author{}
class AuthorNumber{}
class Name {}
class ShortBio{}

class Librarian{}

class Reader{}

Author "1.." -up- "1" Librarian: searches for <
Author "1.." -up- "1" Reader: searches for <

Author *-- AuthorNumber
Author *-- Name
Author *-- ShortBio

@enduml
