@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

actor "Librarian" as Librarian
participant ":System" as System

activate Librarian

Librarian -> System: Requests to search Readers by phone number
activate System
System -> System: Retrieve Readers with the specified phone number
System --> Librarian: Display list of Readers matching the phone number

deactivate System
@enduml
