@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

actor "Librarian" as Librarian
participant ":System" as System

activate Librarian

Librarian -> System: asks to get reader details by reader number
System --> Librarian: reader details and informs operation success
@enduml