@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

actor "Librarian" as Librarian
participant ":System" as System

activate Librarian

Librarian -> System: Requests to augment reader profile\nwith a funny quote based on date of birth
activate System
System -> System: Retrieve reader's date of birth
System -> System: Generate or retrieve a funny quote based on date of birth
System -> System: Update reader profile with the funny quote
System --> Librarian: Inform operation success and display updated profile

deactivate System
@enduml
