@startuml
'https://plantuml.com/sequence-diagram

hide circle
hide methods
left to right direction


class User{
    -username
    -fullName
    -password
    -rePassword
    -authorities
}

class Roles{
    - Admin
    - Librarian
    - Reader
}

User "1" --- "1..*" Roles: has

@enduml