@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

actor "Librarian" as Librarian
participant ":System" as System

activate Librarian

Librarian -> System: Requests to register a book with title, author, and optional cover photo
alt If cover photo is provided
    System -> System: Save book details and cover photo
else If no cover photo
    System -> System: Save book details
end
System --> Librarian: Informs operation success

@enduml
