@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

actor "Librarian" as Librarian
participant ":System" as System

activate Librarian

Librarian -> System: Requests average number of lendings\nper genre for a certain month
activate System
System -> System: Retrieve lending data for the specified month
System -> System: Calculate average lendings per genre
System --> Librarian: Display average lendings per genre for the specified month

deactivate System
@enduml
