@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

actor "Librarian" as Librarian
participant ":System" as System

activate Librarian

Librarian -> System: Requests monthly lending per reader\nfor a certain period
activate System
System -> System: Retrieve lending data for the specified period
System -> System: Calculate monthly lending per reader
System --> Librarian: Display monthly lending per reader\nfor the specified period

deactivate System
@enduml
