@startuml
'autonumber'

actor "Librarian" as Librarian
participant ":System" as System
activate Librarian

Librarian -> System: Requests to know the Top 5 readers
activate System
System -> System: Identifies the Top 5 readers
System --> Librarian: Displays the Top 5 readers
deactivate System
@enduml
