@startuml
 'https://plantuml.com/class-diagram

 hide circle
 skinparam classAttributeIconSize 0

title Vista lógica nível 2

component "<System>" {
           [User Service]
           [Book Service]
           [Lending Service]
           [User Database]
           [Book Database]
           [Lending Database]
}


'"<System>" ~up~ boundary
[User Service] ~up~ boundary1
[User Service] -down(0- [User Database] : SQL
[Book Service] ~up~ boundary2
[Book Service] -down(0- [Book Database] : SQL
[Lending Service] ~up~ boundary3
[Lending Service] -down(0- [Lending Database] : SQL
@enduml
