@startuml
 'https://plantuml.com/class-diagram

 hide circle
 skinparam classAttributeIconSize 0

title Vista lógica nível 2

component System {
 rectangle BE {
 }

 rectangle DB {
  }
}

BE -up- DB : SQL

System ~up~ boundary


@enduml
