@startuml
 'https://plantuml.com/class-diagram

 hide circle
 skinparam classAttributeIconSize 0


component System {
 rectangle BE {
 }
 rectangle DB {
  }
}
component Http_Client {

}

boundary     "boundary"    as boundaryVeryLOOOOOOOOOOOOOOOOOOOg
System -- boundary


@enduml
