@startuml
' https://plantuml.com/class-diagram

hide circle

title Vista Lógica Nível 1

' Definir o componente principal LMS
component LMS

' Definir as "bolinhas" externas que representam os microserviços
interface "Reader Service" as US
interface "Book Service" as BS
interface "Lending Service" as LS
interface "Authentication Service" as AS

' Colocar os microserviços em cima do LMS e conectá-los com linhas verticais retas para cima
US -down- LMS
BS -down- LMS
LS -down- LMS
AS -down- LMS

@enduml
