@startuml
 'https://plantuml.com/class-diagram

title Vista fisica nível 3

 hide circle
 skinparam classAttributeIconSize 0

node [????????????????????????]

node {
    frame "Microservices" {
          [User and Reader Service]
          [Book Service]
          [Lending Service]
        }
}

[User and Reader Service] --> "User Database"
[Book Service] --> "Book Database"
[Lending Service] --> "Lending Database"

@enduml