@startuml

'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

participant "Anonymous:HTTPClient" as HTTPClient
participant "handler:RouteHandler" as System
participant ":ReaderController" as Ctrl
participant "service:ReaderService" as Service
participant "repo:ReaderRepository" as Repo
participant "mapper:EditReaderMapper" as EditReaderMapper
participant "mapper:ReaderViewMapper" as ReaderViewMapper
participant "reader:Reader" as Reader
participant "result:HttpResult" as Result

activate HTTPClient

HTTPClient -> System: POST/readers(data)
System -> Ctrl: createReader(resource)
Ctrl -> Service: createReader(resource)
Service -> Service: validateCreateReaderRequest(resource)
Service --> Service: ok
Service -> EditReaderMapper: create(resource)
EditReaderMapper --> Reader**: create(EditReaderRequest request)
EditReaderMapper --> Service: reader
Service -> Repo: save(reader)
Repo --> Service: reader
Service --> Ctrl: reader
Ctrl -> ReaderViewMapper: toReaderView(reader)
ReaderViewMapper --> Ctrl: readerView
Ctrl --> Result**: create(201)
Ctrl --> System: result
System -> System: setHttpResult(resp, result)
System --> HTTPClient: resp

@enduml
