@startuml
 'https://plantuml.com/class-diagram

hide circle
skinparam classAttributeIconSize 0
title Vista de processos nível 1

participant " " as Anonymous
participant ":LMS" as System

Anonymous o-> System: POST/authors(data)
System -->o Anonymous: 201

Anonymous o-> System: PUT/authors(data)
System -->o Anonymous: 200

Anonymous o-> System: GET/authors/{id}
System -->o Anonymous: 200 and shows author data

Anonymous o-> System: GET/authors/name/{name}
System -->o Anonymous: 200 and shows author data

Anonymous o-> System: POST/books(data)
System -->o Anonymous: 201

Anonymous o-> System: PUT/books(data)
System -->o Anonymous: 200

Anonymous o-> System: GET/Books/{isbn}
System -->o Anonymous: 200 and book details

Anonymous o-> System: GET/books/genre/{genre}
System -->o Anonymous: 200 and books list by genre

Anonymous o-> System: POST/readers(data)
System -->o Anonymous: 201

Anonymous o-> System: PUT/readers(data)
System -->o Anonymous: 200

Anonymous o-> System: GET/readers/{id}
System -->o Anonymous: 200 and readers details

Anonymous o-> System: GET/readers/name/{name}
System -->o Anonymous: 200 and readers list by name

Anonymous o-> System: POST /lend(data)
System -->o Anonymous: 201 and return date

Anonymous o-> System: POST /return(data)
System -->o Anonymous: 201

Anonymous o-> System: GET /lend/{lendingId}
System -->o Anonymous: 200

Anonymous o-> System: POST /api/authors
System -->o Anonymous: 201

Anonymous o-> System: GET api/authors/{authorid}/books
System -->o Anonymous: 200 and book list

Anonymous o-> System: GET /{authorId}/co-authors
System -->o Anonymous: 200 and co-authors list

Anonymous o-> System: GET /authors/top-5
System -->o Anonymous: 200 and top-5 authors list

Anonymous o-> System: PUT /books (data)
System -->o Anonymous: 200

Anonymous o-> System: GET /books?title=(title)
System -->o Anonymous: 200 and books list by title

Anonymous o-> System: GET api/books/top-books
System -->o Anonymous: 200 and top-5 books list

Anonymous o-> System: GET /books/top-genres
System -->o Anonymous: 200 and top genres list

Anonymous o-> System: GET/top-readers
System -->o Anonymous: 200 and top readers list

Anonymous o-> System: GET /{readerId}/suggestions
System -->o Anonymous: 200 and suggestions list

Anonymous o-> System: GET /api/lendings/average-per-genre/{date}
System -->o Anonymous: 200 and average lendings per genre by date list

Anonymous o-> System: GET /api/lendings/average
System -->o Anonymous: 200 and average lending duration

Anonymous o-> System: GET /api/lendings/overdue
System -->o Anonymous: 200 and overdue lendings list by tardiness

@enduml