@startuml
' Definindo os participantes
participant "HTTP Client" as client
participant "reader[0] : Reader" as reader0
participant "reader[1] : Reader" as reader1

client -> reader0: POST /readers {readerData, photo}
activate reader0

' Reader 0 salva os dados
reader0 -> reader0: save(readerData, photo)

' Resposta inicial ao cliente (tracejada, pois o processo ainda está em andamento)
reader0 -[#gray,dashed]-> client: 201 Created (Dados salvos na primeira instância)

' Replicação dos dados para a outra instância (espelhamento)
reader0 -> reader1: POST /readers(readerData, photo)
activate reader1
reader1 -> reader1: save(readerData, photo)
deactivate reader1

' Reader 1 envia a resposta final ao cliente indicando que a replicação foi bem-sucedida
reader1 --> client: 201 Created (Replicação bem-sucedida)

deactivate reader0

@enduml
