@startuml
'https://plantuml.com/class-diagram

hide circle
skinparam classAttributeIconSize 0

class Reader{
    - id
    - name
    - email
    - dateOfBirth
    - phoneNumber
    - GDBRConsent
    + getVersion()
    Reader(name, email, dateOfBirth, phoneNumber, GDBRConsent)
}

class ReaderController
{
    + getTopReaders()
}
class ReaderServiceImpl
{
    + getTopReaders(topN: int)
}
class ReaderViewMapper
{
    + toReaderView(reader)
}

class ReaderRepository
{
    + findTopReaders(pageable, startDate, endDate)
}

class ReaderView
{
    - name
    - email
}

ReaderController ..> ReaderServiceImpl
ReaderServiceImpl ..> ReaderRepository
ReaderController ..> ReaderViewMapper
ReaderRepository "1" --> "0..*" Reader: records
ReaderRepository ..> ReaderView
ReaderRepository ..> Reader
ReaderViewMapper ..> ReaderView
ReaderView ..> Reader

@enduml
