@startuml

'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

participant "Anonymous:HTTPClient" as HTTPClient
participant "handler:RouteHandler" as System
participant ":BookController" as Ctrl
participant "service:BookService" as Service
participant "repo:BookRepository" as Repo
participant "repo:GenreRepository" as GenreRepo
participant "mapper:EditBookMapper" as EditBookMapper
participant "book:Book" as Book
participant "result:HttpResult" as Result
participant "mapper:BookViewMapper" as ViewMapper

activate HTTPClient


HTTPClient -> System: PUT/books(data)
System -> Ctrl: updateBook(resource)
Ctrl -> Service: updateBook(resource)
Service -> Repo: findById(bookId)
Repo --> Service: book
Service -> GenreRepo: findById(resource.getGenre().getId())
GenreRepo --> Service: genre
Service -> Book: update(newData)
Book --> Service: book
Service -> Repo: save(book)
Repo --> Service: book
Service --> Ctrl: book
Ctrl -> ViewMapper: toBookView(book)
ViewMapper --> Ctrl: bookView
Ctrl --> Result**: update(200, bookView)
Ctrl --> System: result
System -> System: setHttpResult(resp, result)
System --> HTTPClient: resp

@enduml
